name: someappname
description: Production-ready app template based on Flutter and Rust

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.1.0

environment:
  sdk: ">=3.0.2"

dependencies:
  flutter:
    sdk: flutter
  bitsdojo_window: ^0.1.5
  flutter_rust_bridge: ^1.77.1
  ffi: ^2.0.1
  uuid: ^3.0.7
  meta: ^1.8.0
  easy_localization: ^3.0.1
  easy_localization_loader: ^1.0.1
  messagepack: ^0.2.1
  universal_platform: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  ffigen: ^8.0.2
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  windows:
    image_path: "build/app_icons/windows.png"
    generate: true
    icon_size: 256
  android: "ic_launcher"
  image_path_android: "build/app_icons/android.png"
  macos:
    image_path: "build/app_icons/macos.png"
    generate: true
  ios: true
  image_path_ios: "build/app_icons/ios.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "build/app_icons/web.png"
