// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.77.1.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import 'bridge_generated.io.dart'
    if (dart.library.html) 'bridge_generated.web.dart';
import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';

abstract class Bridge {
  Stream<String> prepareViewmodelUpdateStream({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kPrepareViewmodelUpdateStreamConstMeta;

  Stream<ViewUpdate> prepareViewUpdateStream({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kPrepareViewUpdateStreamConstMeta;

  MutexEndpointsOnRustThread prepareChannels({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kPrepareChannelsConstMeta;

  Future<void> layEndpointsOnRustThread(
      {required MutexEndpointsOnRustThread rustOpaque, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kLayEndpointsOnRustThreadConstMeta;

  Future<void> startRustLogic({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kStartRustLogicConstMeta;

  void sendUserAction(
      {required String taskAddress,
      required Serialized serialized,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSendUserActionConstMeta;

  /// This function is meant to be called when Dart's hot restart is triggered in debug mode.
  void cleanViewmodel({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kCleanViewmodelConstMeta;

  Serialized? readViewmodel({required String itemAddress, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kReadViewmodelConstMeta;

  DropFnType get dropOpaqueMutexEndpointsOnRustThread;
  ShareFnType get shareOpaqueMutexEndpointsOnRustThread;
  OpaqueTypeFinalizer get MutexEndpointsOnRustThreadFinalizer;
}

@sealed
class MutexEndpointsOnRustThread extends FrbOpaque {
  final Bridge bridge;
  MutexEndpointsOnRustThread.fromRaw(int ptr, int size, this.bridge)
      : super.unsafe(ptr, size);
  @override
  DropFnType get dropFn => bridge.dropOpaqueMutexEndpointsOnRustThread;

  @override
  ShareFnType get shareFn => bridge.shareOpaqueMutexEndpointsOnRustThread;

  @override
  OpaqueTypeFinalizer get staticFinalizer =>
      bridge.MutexEndpointsOnRustThreadFinalizer;
}

class Serialized {
  final Uint8List bytes;
  final String formula;

  const Serialized({
    required this.bytes,
    required this.formula,
  });
}

class ViewUpdate {
  final String displayAddress;
  final Serialized serialized;

  const ViewUpdate({
    required this.displayAddress,
    required this.serialized,
  });
}
